// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH9rgW7o2AukFNR08OJyae4CGrhsW3V5s',
    appId: '1:705027437169:web:4bffd01b982c4f7a78a1d0',
    messagingSenderId: '705027437169',
    projectId: 'fire-demo-2dbb6',
    authDomain: 'fire-demo-2dbb6.firebaseapp.com',
    storageBucket: 'fire-demo-2dbb6.firebasestorage.app',
    measurementId: 'G-3D8JYHEEQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOeaiJ3f3mXVWg14tYlT9ZuKufbHTXvSk',
    appId: '1:705027437169:android:febca32dfaa6871678a1d0',
    messagingSenderId: '705027437169',
    projectId: 'fire-demo-2dbb6',
    storageBucket: 'fire-demo-2dbb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACVDcUVUwjTwwKfHBU4eiVhJjLdFqTg1s',
    appId: '1:705027437169:ios:4810ca5c1443e84e78a1d0',
    messagingSenderId: '705027437169',
    projectId: 'fire-demo-2dbb6',
    storageBucket: 'fire-demo-2dbb6.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACVDcUVUwjTwwKfHBU4eiVhJjLdFqTg1s',
    appId: '1:705027437169:ios:6678da71c158138b78a1d0',
    messagingSenderId: '705027437169',
    projectId: 'fire-demo-2dbb6',
    storageBucket: 'fire-demo-2dbb6.firebasestorage.app',
    iosBundleId: 'com.example.persianCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH9rgW7o2AukFNR08OJyae4CGrhsW3V5s',
    appId: '1:705027437169:web:73a709b0edeec2fc78a1d0',
    messagingSenderId: '705027437169',
    projectId: 'fire-demo-2dbb6',
    authDomain: 'fire-demo-2dbb6.firebaseapp.com',
    storageBucket: 'fire-demo-2dbb6.firebasestorage.app',
    measurementId: 'G-5VWWV5J8LG',
  );
}
